#!/usr/bin/env python3

# Generated with OpenCode.

import argparse
import json
import sys

def parse_args():
    parser = argparse.ArgumentParser(description=(
        "Prints a table of the number of reached and triggered bugs for each "
        "library in a bugs.json summary file."
    ))
    parser.add_argument("json",
        help="The experiment summary JSON file generated by the benchd tool.")
    return parser.parse_args()

def count_by_library(data):
    per_library = {}
    for fuzzer, f_data in data.get("results", {}).items():
        for library, l_data in f_data.items():
            reached, triggered = per_library.setdefault(library, (set(), set()))
            for candidate in l_data.values():
                for trial in candidate.values():
                    reached.update(trial.get("reached", {}))
                    triggered.update(trial.get("triggered", {}))
    return per_library

def main():
    args = parse_args()
    with open(args.json) as f:
        data = json.load(f)
    per_library = count_by_library(data)
    print(f"{'Library':<16}{'Reached':>10}{'Triggered':>12}")
    for library in sorted(per_library):
        reached, triggered = per_library[library]
        print(f"{library:<16}{len(reached):>10}{len(triggered):>12}")

if __name__ == '__main__':
    main()
